spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FinSight
    username: postgres
    password: "FinSight@2026"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # WebSocket / STOMP
  websocket:
    allowed-origins: "*"

server:
  port: 8080

# Allow CORS for the React dev server
spring.mvc.cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"